FROM node:16-alpine

WORKDIR /app

COPY package*.json ./

COPY yarn.lock ./

COPY .env.development ./

COPY .env ./

RUN yarn install

COPY . .

RUN yarn prisma generate

EXPOSE 5000

CMD [ "yarn", "dev" ]