export const MESSAGES = {
  FILE_EMPTY: 'No files were selected.',
  FILE_UPLOADED: 'File uploaded!',
  FILE_SIZE_EXCEEDED: 'File size exceeded 5MB.',
  FILE_INVALID_MIMETYPE: 'Invalid file type.',
  PLAY_GROUND: 'hello! this is playground test successfull!!',
  FIELD_EMPTY: 'One or more fields are empty.',
  WRONG_PASSWORD: 'Wrong password.',
  LOGIN_SUCCESS: 'Login successful!!',
  REGISTER_SUCCESS: 'Registered successfully!!',
  WRONG_BEARER: 'Wrong bearer token.',
  UNAUTHORIZED: 'Unauthorized!!',
  INSUFFICIENT_PERMISSION: 'Insufficient permission!!',
  DISTRIBUTOR_TOKEN_SUCCESS: 'Token successfully generated!!',
  DISTRIBUTOR_TOKEN_DELETED: 'Token successfully deleted!!',

  CATEGORY_CREATED: 'Category created!!',
  CATEGORY_DELETED: 'Category deleted!!',
  CATEGORY_UPDATED: 'Category updated!!',
  SERVER_ERROR: 'Something went wrong',
  FILE_DELETED: 'File deleted!!',
  FILE_NOT_FOUND: 'File not found!!',
  FILE_UPDATED: 'File Updated!!',
  FILE_LIMIT_EXCEEDED:
    'It exceeds your file limit! Please buy a better plan.',
  FOLDER_CREATED: 'Folder created!!',
  INVALID_ROLE_ERROR: 'Invalid role!!',
  USER_EXISTS: 'User already exists!!',
  USER_CREATED: 'User created successfully!!',
  USER_DELETED: 'User deleted successfully!!',
  USER_UPDATED: 'User updated successfully!!',
  PROFILE_CREATED: 'Profile created successfully!!',
  PROFILE_DELETED: 'Profile deleted successfully!!',
};
