export const MESSAGES = {
  FILE_EMPTY: 'No files were selected.',
  FILE_UPLOADED: 'File uploaded!',
  PLAY_GROUND: 'hello! this is playground test successfull!!',
  FIELD_EMPTY: 'One or more fields are empty.',
  WRONG_PASSWORD: 'Wrong password.',
  LOGIN_SUCCESS: 'Login successful!!',
  REGISTER_SUCCESS: 'Registered successfully!!',
  WRONG_BEARER: 'Wrong bearer token.',
  UNAUTHORIZED: 'Unauthorized!!',
  INSUFFICIENT_PERMISSION: 'Insufficient permission!!',
  DISTRIBUTOR_TOKEN_SUCCESS: 'Token successfully generated!!',

  CATEGORY_CREATED: 'Category created!!',
  CATEGORY_DELETED: 'Category deleted!!',
  CATEGORY_UPDATED: 'Category updated!!',
  SERVER_ERROR: 'Something went wrong',
  FILE_DELETED: 'File deleted!!',
  FILE_NOT_FOUND: 'File not found!!',
  FILE_UPDATED: 'File Updated!!',
  INVALID_ROLE_ERROR: 'Invalid role!!',
  USER_EXISTS: 'User already exists!!',
  USER_CREATED: 'User created successfully!!',
  USER_DELETED: 'User deleted successfully!!',
  USER_UPDATED: 'User updated successfully!!',
};
